package gestordefinancas.view;

import gestordefinancas.dao.EntradaDAO;
import gestordefinancas.model.Entrada;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;

public class GestorDeFinancasGUI extends JFrame {

    // Lista para armazenar os IDs das entradas
    private final List<Integer> listaIds = new ArrayList<>();

    public GestorDeFinancasGUI() {
        initComponents();
        SwingUtilities.invokeLater(this::carregarTabela); // Carrega os dados existentes na tabela após a GUI ser visível
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        jPanel1 = new JPanel();
        jScrollPane1 = new JScrollPane();
        tabela = new JTable();
        jLabel6 = new JLabel();
        labelRecebido = new JLabel();
        jLabel7 = new JLabel();
        labelGastos = new JLabel();
        jLabel8 = new JLabel();
        labelDiferenca = new JLabel();
        jPanel2 = new JPanel();
        btnApagar = new JButton();
        btnCadastrar = new JButton();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        btnGanho = new JToggleButton();
        btnDespesa = new JToggleButton();
        txtData = new JFormattedTextField();
        txtValor = new JTextField();
        cbClassificacao = new JComboBox<>();
        txtNome = new JTextField();
        jLabel1 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabela.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Classificação", "Valor", "Data de Entrada", "Data de Cadastrado", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Recebido:");

        labelRecebido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRecebido.setText("R$ 0");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Gastos:");

        labelGastos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelGastos.setText("R$ 0");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Diferença:");

        labelDiferenca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDiferenca.setText("R$ 0");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnApagar.setBackground(new java.awt.Color(51, 255, 204));
        btnApagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(51, 255, 204));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Classificação:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Valor:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Data Entrada:");

        btnGanho.setBackground(new java.awt.Color(51, 255, 51));
        btnGanho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGanho.setText("Ganho(+)");
        btnGanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanhoActionPerformed(evt);
            }
        });

        btnDespesa.setBackground(new java.awt.Color(255, 51, 51));
        btnDespesa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDespesa.setText("Despesa(-)");
        btnDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespesaActionPerformed(evt);
            }
        });

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbClassificacao.setModel(new DefaultComboBoxModel<>(new String[] { "", "CASA ", "COMPRAS", "SAÚDE", "AUTOMÓVEL", "ALIMENTAÇÃO", "BEM ESTAR", "INVESTIMENTO", "SALÁRIO", "OUTROS" }));

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Finanças Anual - Seu José");

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnGanho, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(btnDespesa, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
                            .addGap(182, 182, 182))
                        .addGroup(GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNome)
                                .addComponent(txtValor)
                                .addComponent(txtData)
                                .addComponent(cbClassificacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCadastrar, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                        .addComponent(btnApagar, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbClassificacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtData, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGanho)
                    .addComponent(btnDespesa))
                .addGap(29, 29, 29)
                .addComponent(btnCadastrar)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApagar)
                .addContainerGap())
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 249, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelRecebido, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelGastos, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDiferenca, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 738, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelRecebido)
                    .addComponent(jLabel7)
                    .addComponent(labelGastos)
                    .addComponent(jLabel8)
                    .addComponent(labelDiferenca))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanhoActionPerformed
        if (btnGanho.isSelected()) {
            btnDespesa.setEnabled(false);
        } else {
            btnDespesa.setEnabled(true);
        }
    }//GEN-LAST:event_btnGanhoActionPerformed

    private void btnDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespesaActionPerformed
        if (btnDespesa.isSelected()) {
            btnGanho.setEnabled(false);
        } else {
            btnGanho.setEnabled(true);
        }
    }//GEN-LAST:event_btnDespesaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome = txtNome.getText().trim();
        String classificacao = (String) cbClassificacao.getSelectedItem();
        String valorString = txtValor.getText().trim();
        String campoData = txtData.getText().trim();
        String tipo = "";

        // Valida os campos obrigatórios
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um nome.", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (valorString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um valor.", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(campoData.equals("/  /")){
            JOptionPane.showMessageDialog(this, "O campo Data deve ser preenchido.", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (classificacao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma classificação.", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!btnGanho.isSelected() && !btnDespesa.isSelected()){
            JOptionPane.showMessageDialog(this, "Selecione o tipo de entrada: Ganho ou Despesa.", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(btnGanho.isSelected()){
            tipo = "GANHO";
        }
        if(btnDespesa.isSelected()){
            tipo = "DESPESA";
        }

        try {
            // Formata o valor e a data
            double valor = Double.parseDouble(valorString);

            DateTimeFormatter formatoEntrada = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dataEntrada = LocalDate.parse(campoData, formatoEntrada);

            //Cria uma nova entrada e salva no banco de dados
            EntradaDAO dao = new EntradaDAO();
            Boolean resultado = dao.inserirCadastro(nome, classificacao, valor, dataEntrada, LocalDate.now(), tipo);

            if(resultado){
                showTemporaryMessage("Cadastro inserido com sucesso!", 1000);
            }
            else{
                JOptionPane.showMessageDialog(this, "Erro no cadastro!", "Erro", JOptionPane.ERROR_MESSAGE);
            }

            // Limpa os campos e carregar a tebela com o novo registro
            limparCampos();
            carregarTabela();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um valor válido.", "Erro", JOptionPane.WARNING_MESSAGE);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira uma data válida no formato dd/MM/yyyy.",  "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Função para limpar os campos após o cadastro
    private void limparCampos(){
        txtNome.setText("");
        txtValor.setText("");
        txtData.setText("");
        cbClassificacao.setSelectedIndex(0);
        btnGanho.setEnabled(true);
        btnDespesa.setEnabled(true);
    }

    // Função para carregar os dados da tabela a partir do banco de dados
    private void carregarTabela() {
        EntradaDAO entradaDAO = new EntradaDAO();
        listaIds.clear();

        try {
            // Somas os ganhos e despesas para calcular a diferença
            float somaGanhos = 0;
            float somaDespesas = 0;

            // Obtém a lista de todas as entradas cadastradas
            List<Entrada> entradas = entradaDAO.buscarEntradas();

            // Limpa a tabela antes de recarregar os dados
            DefaultTableModel modelTabela = (DefaultTableModel) tabela.getModel();
            modelTabela.setRowCount(0);

            // Omitir gastos, ganhos e diferença se não houver entradas
            if (entradas.isEmpty()) {
                showTemporaryMessage("Não há entradas cadastradas até o momento.", 1000);

                jLabel6.setVisible(false);
                labelRecebido.setVisible(false);
                jLabel7.setVisible(false);
                labelGastos.setVisible(false);
                jLabel8.setVisible(false);
                labelDiferenca.setVisible(false);
            }
            else {
                // Adiciona cada entrada como uma linha na tabela
                for (Entrada entrada : entradas) {
                    Object[] row = new Object[]{
                            entrada.getNome(),
                            entrada.getClassificacao(),
                            entrada.getValor(),
                            entrada.getDataEntrada().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                            entrada.getDataCadastro().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                            entrada.getTipo()
                    };
                    modelTabela.addRow(row);

                    listaIds.add(entrada.getId());

                    // Verificar o tipo da entrada
                    if(entrada.getTipo().equalsIgnoreCase("GANHO")){
                        somaGanhos += entrada.getValor();
                    }

                    if(entrada.getTipo().equalsIgnoreCase("DESPESA")){
                        somaDespesas += entrada.getValor();
                    }
                }

                // Tornar os labels e valores visíveis quando houver entradas
                jLabel6.setVisible(true);
                labelRecebido.setVisible(true);
                jLabel7.setVisible(true);
                labelGastos.setVisible(true);
                jLabel8.setVisible(true);
                labelDiferenca.setVisible(true);
            }

            // Exibir na tela as somas e diferença calculadas
            labelRecebido.setText("R$ " + somaGanhos + "");
            labelGastos.setText("R$ " + somaDespesas + "");
            labelDiferenca.setText("R$ " + (somaGanhos - somaDespesas) + "");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados da tabela: " + e.getMessage());
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // Pegar índice da linha escolhida na tabela pelo usuário
        DefaultTableModel modelTabela =  (DefaultTableModel) tabela.getModel();
        int linhaSelecionada = tabela.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma entrada na tabela para apagar.", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirma a exclusão antes de apagar
        int confirma = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja exluir?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirma != JOptionPane.YES_OPTION) {
            return;
        }

        // Obtém o ID da lista de IDs
        int id = listaIds.get(linhaSelecionada);
        EntradaDAO dao = new EntradaDAO();

        // Exlcuir entrada com base no id
        Boolean resultado = dao.excluirCadastro(id);

            if(resultado){
                showTemporaryMessage("Entrada apagada com sucesso!", 1000);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir cadastro!", "Erro", JOptionPane.ERROR_MESSAGE);
            }

            carregarTabela();

    }//GEN-LAST:event_btnApagarActionPerformed

    // Mostrar botões de ganho e gasto ao clicar no primeiro campo
    private void txtNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMouseClicked
        btnGanho.setVisible(true);
        btnDespesa.setVisible(true);
    }//GEN-LAST:event_txtNomeMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorDeFinancasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorDeFinancasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorDeFinancasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorDeFinancasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorDeFinancasGUI().setVisible(true);
            }
        });
    }

    // Função para mostrar uma mensagem temporária na tela
    private void showTemporaryMessage(String message, int duration) {
        JOptionPane pane = new JOptionPane(message, JOptionPane.INFORMATION_MESSAGE);
        JDialog dialog = pane.createDialog(this, "Message");
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        Timer timer = new Timer(duration, e -> dialog.dispose());
        timer.setRepeats(false);
        timer.start();
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnApagar;
    private JButton btnCadastrar;
    private JToggleButton btnDespesa;
    private JToggleButton btnGanho;
    private ButtonGroup buttonGroup1;
    private JComboBox<String> cbClassificacao;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private JLabel labelDiferenca;
    private JLabel labelGastos;
    private JLabel labelRecebido;
    private JTable tabela;
    private JFormattedTextField txtData;
    private JTextField txtNome;
    private JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
